[Project]
Name=Saracura OS Customization
Version=1.0
Description=Projeto de personalização da ISO do Ubuntu 24.04 com o Saracura OS.
Author=OgliariNatan
Email=ogliarinatan@example.com

[Scripts]
InstallScript=scripts/install_programas.sh
RemoveScript=scripts/remove_programas.sh
FirstLoginScript=scripts/primeiro-login.sh
PostInstallScript=scripts/pos-instalacao.sh

[Configuration]
KDEConfig=config/kde/kdeglobals
KWinConfig=config/kde/kwinrc
AutostartConfig=config/autostart/saracura-primeiro-login.desktop
SDDMConfig=config/sddm/sddm.conf
SudoersConfig=config/sudoers.d/saracura-patrimonio

[Resources]
WallpaperDir=resources/wallpapers

[Preseed]
PreseedFile=cubic/preseed.cfg

[Documentation]
GuideFile=docs/GUIDE-CUBIC.md
ProgramListFile=docs/LISTA-PROGRAMAS.md
ChangelogFile=docs/CHANGELOG.md