## Configuração do SDDM - Saracura OS
## Copiar para /etc/sddm.conf.d/saracura.conf

[General]
NumLock=on
InputMethod=

[Theme]
Current=breeze

[Users]
MaximumUid=60000
MinimumUid=1000

[Wayland]
SessionDir=/usr/share/wayland-sessions

[X11]
SessionDir=/usr/share/xsessions