[Autologin]
User=saracura
Session=plasma.desktop

[General]
NumLock=on

[Theme]
Current=YourThemeName

[Users]
Maximum=10
Minimum=1

[Wayland]
Enable=false

[Greeter]
Background=/usr/share/backgrounds/logo_PP_saracura_TROCA.png
IconTheme=YourIconThemeName
CursorTheme=YourCursorThemeName